export const PREREQUISITE_SEARCH_REQUEST = "PREREQUISITE_SEARCH_REQUEST";
export const PREREQUISITE_SEARCH_SUCCESS = "PREREQUISITE_SEARCH_SUCCESS";
export const PREREQUISITE_SEARCH_FAIL = "PREREQUISITE_SEARCH_FAIL";

export const RELATIONSHIP_SEARCH_REQUEST = "RELATIONSHIP_SEARCH_REQUEST";
export const RELATIONSHIP_SEARCH_SUCCESS = "RELATIONSHIP_SEARCH_SUCCESS";
export const RELATIONSHIP_SEARCH_FAIL = "RELATIONSHIP_SEARCH_FAIL";

export const DEPENDENCY_SEARCH_REQUEST = "DEPENDENCY_SEARCH_REQUEST";
export const DEPENDENCY_SEARCH_SUCCESS = "DEPENDENCY_SEARCH_SUCCESS";
export const DEPENDENCY_SEARCH_FAIL = "DEPENDENCY_SEARCH_FAIL";
